### ISSUE TITLE
Implement E2E test for migration to Espresso Sequencer

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/nitro-espresso-integration#162]
The E2E should have at least the following steps. Some of the ordering can be changed. For example the Espresso sequencer just needs to be started before the the upgrade is executed.

### Prerequisites
-  [x] #205
   + This is required to be able to start upstream nitro at the start of the migration test.
- [x] #206
   + This will make it easier to test because we first test upgrading a single node instead of having to upgrade sequencer, poster, validator, etc.

### Tasks
- [x] Start up the espresso sequencer 
- [x] Run `test-node.bash` to start up nitro based on upstream docker images of nitro (without our integration). We may have to build the `nitro-node-dev` image locally (because they don't seem to publish it) although it would be nice if it worked with `nitro-node` which is available on dockerhub. I think previously the testnode was needed because the `deploy` binary was used but they are using the `rollupcreator` image for that now. We can probably use the `--simple` flag for the test-node.bash script to simplify the configuration a bit. 
- [x] Shut down the nitro node.
- [x] Start the nitro node in a new docker container, now made from the espresso integration image, but re-using the storage volume from the initial node.
- [x] Deploy new OSP contract
- [x] Run one or more forge script to deploy upgrade actions.
- [x] Run one or more forge scripts to execute the upgrades.
- [x] Somehow observe the upgrade happened in the testnode.
