### ISSUE TITLE
Cleanup and fix TODO's

### ISSUE THREAD

**Issue by Sneh1999** [EspressoSystems/nitro-espresso-integration#328]
- [x] Fix the orbitChain.ts test
- [x] Add comments to all the deprecated and new functions
- [x] Update the scripts to use the contract
